
*** Running vivado
    with args -log fcc_nn_axi_gpio_1_0.vds -m64 -product Vivado -mode batch -messageDb vivado.pb -notrace -source fcc_nn_axi_gpio_1_0.tcl


****** Vivado v2019.2 (64-bit)
  **** SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
  **** IP Build 2700528 on Thu Nov  7 00:09:20 MST 2019
    ** Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.

source fcc_nn_axi_gpio_1_0.tcl -notrace
INFO: [IP_Flow 19-234] Refreshing IP repositories
WARNING: [IP_Flow 19-2248] Failed to load user IP repository '/home/anubhav/workspace-2019/ip_repo/myip_1.0'; Can't find the specified path.
If this directory should no longer be in your list of user repositories, go to the IP Settings dialog and remove it.
INFO: [IP_Flow 19-1700] Loaded user IP repository '/home/anubhav/workspace-2019/custom_ip'.
INFO: [IP_Flow 19-2313] Loaded Vivado IP repository '/tools/Xilinx/Vivado/2019.2/data/ip'.
WARNING: [Vivado 12-818] No files matched '/home/anubhav/workspace-2019/neural_net/neural_net.srcs/sources_1/bd/fcc_nn/ip/fcc_nn_axi_gpio_1_0/fcc_nn_axi_gpio_1_0_board.xdc'
ERROR: [Common 17-55] 'set_property' expects at least one object.
Resolution: If [get_<value>] was used to populate the object, check to make sure this command returns at least one valid object.
INFO: [Common 17-206] Exiting Vivado at Wed Dec  8 11:59:23 2021...
